/*
 * Copyright 2019-2021 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 */


/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v9.0
processor: MIMX8ML8xxxLZ
package_id: MIMX8ML8DVNLZ
mcu_data: ksdk2_0
processor_version: 0.9.1
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
}

/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: m7}
- pin_list:
  - {pin_num: AE6, peripheral: UART3, signal: uart_rx, pin_signal: UART3_RXD, PE: Enabled, HYS: CMOS, PUE: Weak_Pull_Up, FSEL: Slow, DSE: X6}
  - {pin_num: AJ4, peripheral: UART3, signal: uart_tx, pin_signal: UART3_TXD, PE: Enabled, HYS: CMOS, PUE: Weak_Pull_Up, FSEL: Slow, DSE: X6}
  - {pin_num: AH19, peripheral: GPT1, signal: 'gpt_capture, 1', pin_signal: SAI3_TXC, PE: Enabled, PUE: Weak_Pull_Up, DSE: X6}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BOARD_InitPins(void) {                                /*!< Function assigned for the core: Cortex-M7F[m7] */
    IOMUXC_SetPinMux(IOMUXC_SAI3_TXD_GPT1_CAPTURE2, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI3_TXD_GPT1_CAPTURE2, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);

    IOMUXC_SetPinMux(IOMUXC_SAI3_RXC_GPT1_CLK, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI3_RXC_GPT1_CLK, IOMUXC_SW_PAD_CTL_PAD_DSE(3U));

    IOMUXC_SetPinMux(IOMUXC_I2C3_SDA_GPT3_CLK, 0U);
    IOMUXC_SetPinConfig(IOMUXC_I2C3_SDA_GPT3_CLK, IOMUXC_SW_PAD_CTL_PAD_DSE(3U));


    /*IOMUXC_SetPinMux(IOMUXC_SAI3_RXD_GPIO4_IO30, 0U);
    IOMUXC_SetPinConfig(IOMUXC_SAI3_RXD_GPIO4_IO30, 
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);*/


                        
                        /*
    IOMUXC_SetPinMux(IOMUXC_UART3_RXD_UART3_RX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_UART3_RXD_UART3_RX, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);
    IOMUXC_SetPinMux(IOMUXC_UART3_TXD_UART3_TX, 0U);
    IOMUXC_SetPinConfig(IOMUXC_UART3_TXD_UART3_TX, 
                        IOMUXC_SW_PAD_CTL_PAD_DSE(3U) |
                        IOMUXC_SW_PAD_CTL_PAD_PUE_MASK |
                        IOMUXC_SW_PAD_CTL_PAD_PE_MASK);*/
}

#if 0
void rfnm_init_rba_pins(void) {

    // RFNM_DGB_GPIO4_22
    IOMUXC_SetPinMux(IOMUXC_SAI2_RXC_GPIO4_IO22, 0U);
    // RFNM_DGB_GPIO4_23
    IOMUXC_SetPinMux(IOMUXC_SAI2_RXD0_GPIO4_IO23, 0U);
    // RFNM_DGB_GPIO4_31
    IOMUXC_SetPinMux(IOMUXC_SAI2_TXFS_GPIO4_IO24, 0U);
    // RFNM_DGB_GPIO4_9
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD7_GPIO4_IO09, 0U);
    // RFNM_DGB_GPIO4_0
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXFS_GPIO4_IO00, 0U);
    // RFNM_DGB_GPIO4_1
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXC_GPIO4_IO01, 0U);
    // RFNM_DGB_GPIO4_2
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD0_GPIO4_IO02, 0U);
    // RFNM_DGB_GPIO4_4
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD2_GPIO4_IO04, 0U);
    // RFNM_DGB_GPIO4_5
    IOMUXC_SetPinMux(IOMUXC_SAI1_RXD3_GPIO4_IO05, 0U);

}
#endif
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
